from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('GT1151', src, depend = ['PKG_USING_GT1151'], CPPPATH = CPPPATH)

Return('group')